-- Verificación de la foto de perfil (020) con usuarios FICTICIOS. Termina con un error a propósito.
do $fn$
declare
  ua uuid := 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
  ub uuid := 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
  r text := E'\n'; n int; ok boolean; j jsonb; u text;
  good text := 'https://lh3.googleusercontent.com/a/ACg8ocKxyz123=s96-c';
begin
  insert into auth.users (id, email) values (ua, 'a@test.invalid'), (ub, 'b@test.invalid');
  reset role; perform set_config('request.jwt.claims', json_build_object('sub', ua, 'role', 'authenticated')::text, true); set local role authenticated;
  perform public.crear_perfil_social('alice_x');
  reset role; perform set_config('request.jwt.claims', json_build_object('sub', ub, 'role', 'authenticated')::text, true); set local role authenticated;
  perform public.crear_perfil_social('bob_x');
  ok := false; begin perform public.establecer_avatar('https://evil.example.com/track.png'); exception when others then ok := true; end; r := r || case when ok then 'OK   ' else 'FALLO' end || ' no debe poder: foto de otra web' || E'\n';
  ok := false; begin perform public.establecer_avatar('http://lh3.googleusercontent.com/a/abc'); exception when others then ok := true; end; r := r || case when ok then 'OK   ' else 'FALLO' end || ' no debe poder: foto con http' || E'\n';
  ok := false; begin perform public.establecer_avatar('https://lh3.googleusercontent.com.evil.com/a'); exception when others then ok := true; end; r := r || case when ok then 'OK   ' else 'FALLO' end || ' no debe poder: foto con truco de dominio' || E'\n';
  ok := false; begin perform public.establecer_avatar('javascript:alert(1)'); exception when others then ok := true; end; r := r || case when ok then 'OK   ' else 'FALLO' end || ' no debe poder: foto con javascript' || E'\n';
  ok := false; begin update public.perfil_social set avatar_url = 'https://lh3.googleusercontent.com/a/x' where user_id = ub; get diagnostics n = row_count; if n = 0 then raise exception 'sin filas'; end if; exception when others then ok := true; end; r := r || case when ok then 'OK   ' else 'FALLO' end || ' no debe poder: escribir avatar_url directamente' || E'\n';
  perform public.establecer_avatar(good);
  select avatar_url into u from public.perfil_social where user_id = ub;
  r := r || case when coalesce((u = good), false) then 'OK   ' else 'FALLO' end || ' foto de Google guardada' || E'\n';
  reset role; perform set_config('request.jwt.claims', json_build_object('sub', ua, 'role', 'authenticated')::text, true); set local role authenticated;
  reset role; update public.perfil_social set share_metrics_ok = true, share_metrics_at = now(), share_metrics_version = 'v0'; reset role; perform set_config('request.jwt.claims', json_build_object('sub', ua, 'role', 'authenticated')::text, true); set local role authenticated;
  perform public.solicitar_amistad('bob_x');
  select count(*) into n from public.buscar_usuarios('bob') where avatar_url = good;
  r := r || case when coalesce((n = 1), false) then 'OK   ' else 'FALLO' end || ' otros ven la foto en la búsqueda' || E'\n';
  reset role; perform set_config('request.jwt.claims', json_build_object('sub', ub, 'role', 'authenticated')::text, true); set local role authenticated;
  perform public.responder_solicitud((select id from public.mis_amistades() where username = 'alice_x'), true);
  select count(*) into n from public.mis_amistades() where username = 'alice_x' and avatar_url is null;
  r := r || case when coalesce((n = 1), false) then 'OK   ' else 'FALLO' end || ' quien no tiene foto sale sin foto' || E'\n';
  reset role; perform set_config('request.jwt.claims', json_build_object('sub', ua, 'role', 'authenticated')::text, true); set local role authenticated;
  select count(*) into n from public.mis_amistades() where username = 'bob_x' and avatar_url = good;
  r := r || case when coalesce((n = 1), false) then 'OK   ' else 'FALLO' end || ' la foto sale en la lista de amistades' || E'\n';
  perform public.establecer_consentimiento('metricas', true, 'v1');
  reset role; perform set_config('request.jwt.claims', json_build_object('sub', ub, 'role', 'authenticated')::text, true); set local role authenticated;
  perform public.establecer_consentimiento('metricas', true, 'v1');
  reset role; perform set_config('request.jwt.claims', json_build_object('sub', ua, 'role', 'authenticated')::text, true); set local role authenticated;
  j := public.resumen_amigo('bob_x');
  r := r || case when coalesce((j->>'avatar_url' = good), false) then 'OK   ' else 'FALLO' end || ' la foto sale en la ficha del amigo' || E'\n';
  reset role; perform set_config('request.jwt.claims', json_build_object('sub', ub, 'role', 'authenticated')::text, true); set local role authenticated;
  perform public.establecer_mostrar_foto(false);
  reset role; perform set_config('request.jwt.claims', json_build_object('sub', ua, 'role', 'authenticated')::text, true); set local role authenticated;
  select count(*) into n from public.buscar_usuarios('bob') where avatar_url is null;
  r := r || case when coalesce((n = 1), false) then 'OK   ' else 'FALLO' end || ' al ocultar la foto desaparece en la búsqueda' || E'\n';
  select count(*) into n from public.mis_amistades() where username = 'bob_x' and avatar_url is null;
  r := r || case when coalesce((n = 1), false) then 'OK   ' else 'FALLO' end || ' y en la lista de amistades' || E'\n';
  j := public.resumen_amigo('bob_x');
  r := r || case when coalesce((j->'avatar_url' = 'null'::jsonb), false) then 'OK   ' else 'FALLO' end || ' y en la ficha' || E'\n';
  reset role; perform set_config('request.jwt.claims', json_build_object('sub', ub, 'role', 'authenticated')::text, true); set local role authenticated;
  perform public.establecer_avatar(null);
  select avatar_url into u from public.perfil_social where user_id = ub;
  r := r || case when coalesce((u is null), false) then 'OK   ' else 'FALLO' end || ' se puede quitar la foto' || E'\n';
  -- ===== foto subida por el usuario =====
  reset role;
  insert into storage.objects (bucket_id, name, owner) values ('avatars', ub::text || '/1780000000000.jpg', ub), ('avatars', ua::text || '/1780000000001.jpg', ua);
  reset role; perform set_config('request.jwt.claims', json_build_object('sub', ub, 'role', 'authenticated')::text, true); set local role authenticated;
  ok := false; begin perform public.establecer_foto(ua::text || '/1780000000001.jpg'); exception when others then ok := true; end; r := r || case when ok then 'OK   ' else 'FALLO' end || ' no debe poder: usar la foto de otro usuario' || E'\n';
  ok := false; begin perform public.establecer_foto(ub::text || '/1780000000009.jpg'); exception when others then ok := true; end; r := r || case when ok then 'OK   ' else 'FALLO' end || ' no debe poder: ruta de una foto que no existe' || E'\n';
  ok := false; begin perform public.establecer_foto('../../etc/passwd'); exception when others then ok := true; end; r := r || case when ok then 'OK   ' else 'FALLO' end || ' no debe poder: ruta con trucos' || E'\n';
  ok := false; begin update public.perfil_social set avatar_path = 'x' where user_id = ub; get diagnostics n = row_count; if n = 0 then raise exception 'sin filas'; end if; exception when others then ok := true; end; r := r || case when ok then 'OK   ' else 'FALLO' end || ' no debe poder: escribir avatar_path directamente' || E'\n';
  perform public.establecer_foto(ub::text || '/1780000000000.jpg');
  perform public.establecer_mostrar_foto(true);
  select count(*) into n from public.perfil_social where user_id = ub and avatar_path = ub::text || '/1780000000000.jpg';
  r := r || case when n = 1 then 'OK   ' else 'FALLO' end || ' foto propia subida y guardada' || E'\n';
  ok := false; begin insert into storage.objects (bucket_id, name, owner) values ('avatars', ua::text || '/1780000000002.jpg', ub); exception when others then ok := true; end; r := r || case when ok then 'OK   ' else 'FALLO' end || ' no debe poder: subir a la carpeta de otro' || E'\n';
  ok := false; begin insert into storage.objects (bucket_id, name, owner) values ('avatars', ub::text || '/1780000000003.jpg', ub); ok := true; exception when others then ok := false; end; r := r || case when ok then 'OK   ' else 'FALLO' end || ' puede subir a su propia carpeta' || E'\n';
  reset role; perform set_config('request.jwt.claims', json_build_object('sub', ua, 'role', 'authenticated')::text, true); set local role authenticated;
  select count(*) into n from public.mis_amistades() where username = 'bob_x' and avatar_path = ub::text || '/1780000000000.jpg';
  r := r || case when n = 1 then 'OK   ' else 'FALLO' end || ' los amigos ven la ruta de la foto subida' || E'\n';
  select count(*) into n from public.buscar_usuarios('bob') where avatar_path is not null;
  r := r || case when n = 1 then 'OK   ' else 'FALLO' end || ' y en la búsqueda' || E'\n';
  reset role; perform set_config('request.jwt.claims', json_build_object('sub', ub, 'role', 'authenticated')::text, true); set local role authenticated;
  perform public.establecer_mostrar_foto(false);
  reset role; perform set_config('request.jwt.claims', json_build_object('sub', ua, 'role', 'authenticated')::text, true); set local role authenticated;
  select count(*) into n from public.buscar_usuarios('bob') where avatar_path is null and avatar_url is null;
  r := r || case when n = 1 then 'OK   ' else 'FALLO' end || ' al ocultar la foto tampoco sale la subida' || E'\n';
  reset role; perform set_config('request.jwt.claims', json_build_object('sub', ub, 'role', 'authenticated')::text, true); set local role authenticated;
  perform public.establecer_foto(null);
  select count(*) into n from public.perfil_social where user_id = ub and avatar_path is null;
  r := r || case when n = 1 then 'OK   ' else 'FALLO' end || ' se puede quitar la foto subida' || E'\n';
  reset role; perform set_config('request.jwt.claims', json_build_object('role', 'anon')::text, true); set local role anon;
  ok := false; begin perform public.establecer_avatar(good); exception when others then ok := true; end; r := r || case when ok then 'OK   ' else 'FALLO' end || ' no debe poder: anon: establecer foto' || E'\n';
  reset role;
  raise exception 'RESULTADOS (transacción deshecha, no se ha cambiado nada):%', r;
end $fn$;
